DRLab.Web/Controllers/SampleMatrixController.cs
using DRLab.Data.ViewModels;
using DRLab.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace DRLab.Web.Controllers
{
    public class SampleMatrixController : BaseController
    {
        private readonly IE00T_SampleMatrixService _e00T_SampleMatrixService;
        public SampleMatrixController(IE00T_SampleMatrixService e00T_SampleMatrixService)
        {
            _e00T_SampleMatrixService = e00T_SampleMatrixService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<List<E00T_SampleMatrixViewModel>> GetSampleMatrix(string text)
        {
            return await _e00T_SampleMatrixService.GetAllSampleMatrix(text);
        }
        [HttpPost]
        public async Task<ActionResult> SampleMatrix_Create(E00T_SampleMatrixViewModel data_request)
        {

            if (data_request != null)
            {
                await _e00T_SampleMatrixService.Create(data_request);
            }
            return new OkObjectResult(data_request);
        }
    }
}

DRLab.Web/Views/SampleMatrix/PartialViewAddMatrix.cshtml
@(Html.Kendo().Notification()
    .Name("notificationEdit")
    .Position(p => p.Pinned(true).Top(30).Right(30))
    .Stacking(NotificationStackingSettings.Down)
    .Templates(t =>
    {
        t.Add().Type("success").ClientTemplateID("successTemplate");
        t.Add().Type("error").ClientTemplateID("errorTemplate");
    })
)
@model string
<kendo-dialog name="@Model" title="New Sample Matrix" width="400" modal="true" visible="false">
    <content>
        <form asp-controller="SampleMatrix" asp-action="SampleMatrix_Create" id="createSample_MatrixForm" method="post">
            <div class="row mb-2">
                <div class="col-4">
                    <span style="vertical-align: sub;">Sample Matrix</span>
                </div>
                <div class="col-8">
                    @(Html.Kendo().TextBox()
                    .Name("sampleMatrixInput")
                    .HtmlAttributes(new { placeholder = "Sample Matrix", required = "required", style = "width: 100%" }))
                </div>
            </div>
        </form>
    </content>
    <actions>
        <action text="Cancel">
        </action>
        <action text="Save" title="Save" action="onSaveMatrix" primary="true">
        </action>
    </actions>
    <popup-animation>
        <open duration="500" effects="fade:in" />
        <close duration="500" effects="fade:out" />
    </popup-animation>
</kendo-dialog>
<script>
    function onSaveMatrix() {
        var sampleMatrix = $('#sampleMatrixInput').val();
        console.log(sampleMatrix);
        const requestUrl = "/SampleMatrix/SampleMatrix_Create";
        const data = {
            sampleMatrix: sampleMatrix,
        };
        if ((sampleMatrix != null) && (sampleMatrix != '')) {
            $.post({
                url: requestUrl,
                data: data,
                dataType: 'json',
                success: function (result) {
                    $('#sampleMatrixInput').val("");
                    $('#AddMatrix').data("kendoDialog").close();
                    var notification = $("#notificationEdit").data("kendoNotification");
                    notification.show({
                        message: "Insert Successful"
                    }, "success");
                    $('#AddTestInfo').data("kendoDialog").close();
                },
                error: function () {

                }
            });
        }

        return false;
    }
</script>
<script id="errorTemplate" type="text/x-kendo-template">
    <div class="wrong-pass">
        <img src="@Url.Content("~/Shared/error-icon.png")" />
        <h3>#= title #</h3>
        <p>#= message #</p>
    </div>
</script>
<script id="successTemplate" type="text/x-kendo-template">
    <div class="upload-success">
        <img src="@Url.Content("~/Shared/success-icon.png")" />
        <h3>#= message #</h3>
    </div>
</script>